---
- hosts: all
  user: ubuntu
  sudo: yes
  vars: 
    home: /home/harm
    host_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJtAyXJZ2+M9NVasHcb8Btju8Bf4kGLXU/95gOKsVr1bo5y+EJFCaKe87XolfpeTdEEIlEKsIbFQc+zT+TG6QVb3zIe7Am0e9llzc+XL87FUfXPUT4Jd+lreX0EK/POhOwgRHZ3598Qgpf7LAWKMmuVZvxuoXNpixziAsEZnd8mejEByuDfE00qHD472Ao3KlckbPvOHrdDtTSq6opobOLifbs7mTLOPJjeT6xxVVmkTu62syACm9oPFCFBLrIsKapELbpdQC254LBuc7AMTI/tjt6aZu0OuxltoK/pC2MBgGl8WEnKsMuU4WvJWqvudAb2aZ2KM30I8CsFUgyTte9 root@ns500280.ip-198-100-144.net"
    chromebook_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcV9pZcv4UrapcGDPaa0Y+mlNbReu2U9r9Y18LpyFstvKZR2g1CU46il98+MjEYHOJmYJMxJDndu7zee6vPUVkmXydJAstD362r7Mu/La5pZgRfN0xfOI3ynQVmqRFt00c5WA82FGHAtVn7pAq2VBgBa1y3fuZjtvFiykRFq/HoZreD4HPMzCfyeCLU7zab88WBYGGET8ub5KMM2xeUw0f7eTQEnKZF3RIZpp+JCFeGGhIytOC3GZzIQE3C3rSyyvpVC3MHkr5UQ6i9I7he35pUWwD3H/wdjmFsg0MSwDZfb4iec6YY57pVLUPb9EsFSEOIVMy1qMcYRm0yMx3Bacx chronos@localhost"
  tasks:
    - group: name=admin state=present
    - copy: src=files/sudoer_admin dest=/etc/sudoers.d/admin_group mode=440
    - name: add harm user
      user: name=harm shell=/usr/bin/fish group=admin
    - name: add chromebook key
      authorized_key: user=harm key="{{ chromebook_public_key }}"
    - name: add host key
      authorized_key: user=harm key="{{ host_public_key }}"
    - name: add sane locale
      command: locale-gen en_US.UTF-8
    - command: update-locale LANG=en_US.UTF-8
    - apt: update_cache=yes
    - apt: pkg={{ item }} state=installed
      with_items:
        - man-db
        - fish
        - apt-file
        - htop
        - dnsutils
        - curl
        - ack-grep
        - tmux
        - vim-nox
        - git
        - tig
        - mosh
        - irssi
        - unattended-upgrades
        - build-essential
    - name: Copy the unattended upgrades file
      copy: src=files/50unattended-upgrades dest=/etc/apt/apt.conf.d/49unattended-upgrades

